% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={STATS 382 PROJECT 1},
  pdfauthor={Aditya Kapoor},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{STATS 382 PROJECT 1}
\author{Aditya Kapoor}
\date{2023-03-04}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(e1071)}
\end{Highlighting}
\end{Shaded}

Above is our library code needed to run some functions in this project.

\hypertarget{task-1}{%
\subsubsection{Task 1}\label{task-1}}

\begin{quote}
Convert status and continent to factors in the data frame. Convert
thin\_youth and thin\_child to ordered factors in the data frame. Please
include the code in your project, but you do not need to comment on it
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lifeexp }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"lifeexp\_by\_country.csv"}\NormalTok{, }\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{lifeexp}\SpecialCharTok{$}\NormalTok{status }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{status)}
\NormalTok{lifeexp}\SpecialCharTok{$}\NormalTok{continent }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{continent)}

\NormalTok{lifeexp}\SpecialCharTok{$}\NormalTok{thin\_youth }\OtherTok{\textless{}{-}} \FunctionTok{ordered}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{thin\_youth, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Low"}\NormalTok{,}
    \StringTok{"Medium"}\NormalTok{, }\StringTok{"High"}\NormalTok{))}
\NormalTok{lifeexp}\SpecialCharTok{$}\NormalTok{thin\_child }\OtherTok{\textless{}{-}} \FunctionTok{ordered}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{thin\_child, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Low"}\NormalTok{,}
    \StringTok{"Medium"}\NormalTok{, }\StringTok{"High"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{task-2}{%
\subsubsection{Task 2}\label{task-2}}

\begin{quote}
A quantitative variable that is of interest is schooling. Write a
paragraph summarizing and describing the variable. The explanations
should be such that a person with limited statistical knowledge can
understand.\\
* You should initially check for NA values.\\
* Include relevant graphs (minimally a histogram and a boxplot).\\
* Include detailed descriptions of the graphs.\\
* Include appropriate descriptive statistics (minimally measuring the
center and spread).\\
* Explain what those statistics describe about the data.
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{schooling))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{schooling, }\AttributeTok{right =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{xlim =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{25}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{project-1_files/figure-latex/schooling-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{schooling, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{20}\NormalTok{))}
\FunctionTok{title}\NormalTok{(}\AttributeTok{main =} \StringTok{"Boxplot of schooling"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project-1_files/figure-latex/schooling-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{schooling)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.828989
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{schooling)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  5.0 20.4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{schooling)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    5.00   11.00   13.10   13.01   15.00   20.40
\end{verbatim}

The histogram displays fairly evenly distributed data with a mean of
13.01 and no skew---all of the data are bell-shaped. The spread is a
little bit tighter and centered around the mean, though. The boxplot
demonstrates that the black bar, which represents the median of 13.10,
is nearly in the center. There are no outliers either. According to our
coding, the range (standard deviation) is 2.83 and the mean (center) is
13.01. Also, the range of our results is 5.0 to 20.4, with 50\% of them
occurring between 11 and 15. Together, we may conclude that the data we
have from the collection is fairly evenly distributed. There are no
skews or outliers. The data-plots, for instance, show us that nations
are neither uniform in value or tilted toward the bottom half of the
schooling years. In actuality, the data-plots also inform us that no
country in the dataset is accumulating up school hours at an alarming
rate or is utterly deficient in them. We can concentrate on the overall
image when there are no outliers. With around half of our sample nations
having schooling years between 11 and 15 years, the average length of
education across the countries in our sample set is around 13 years. We
may make more estimates based on the dispersion of our data.We may
estimate that around 95\% of our nations have schooling years that are
within two standard deviations of our average, in this case: 7.34 and
18.66, using our spread, standard deviation, and the 68-95-99.7 rule.

\hypertarget{task-3}{%
\subsubsection{Task 3}\label{task-3}}

\begin{quote}
A categorical variable that is of interest is thin\_youth. Write a
paragraph summarizing and describing the variable. The explanations
should be such that a person with limited statistical knowledge can
understand.\\
* Include at least one relevant graph.\\
* Include a detailed description of the graph.\\
* Include appropriate descriptive statistics (such as frequency).\\
* Explain what those statistics describe about the data.
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{thin\_youth)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    Low Medium   High 
##     59     44     68
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{thincounts }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{thin\_youth)}
\NormalTok{thinplot }\OtherTok{\textless{}{-}} \FunctionTok{barplot}\NormalTok{(thincounts, }\AttributeTok{xlab =} \StringTok{"Thinness Category"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Frequency"}\NormalTok{,}
    \AttributeTok{main =} \StringTok{"Frequnecy of Thinness Amongst Those Aged 10{-}19"}\NormalTok{,}
    \AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{70}\NormalTok{))}
\FunctionTok{text}\NormalTok{(}\AttributeTok{x =}\NormalTok{ thinplot, }\AttributeTok{y =}\NormalTok{ thincounts, }\AttributeTok{label =}\NormalTok{ thincounts, }\AttributeTok{pos =} \DecValTok{3}\NormalTok{,}
    \AttributeTok{cex =} \DecValTok{1}\NormalTok{, }\AttributeTok{col =} \StringTok{"black"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project-1_files/figure-latex/thin_youth-1.pdf}

This barplot displays the frequency counts for the various categories of
thinness across all nations. Thus far, it appears to have two peaks at
both low and high frequencies, with the HIGH category having the highest
frequency and the MID category having the lowest.

By examining the data above, we can more clearly identify the frequency.
Here, we can see that the frequencies for the following
categories---Low, Medium, and High---were 59, 44, and 68, respectively.
These frequency figures help to further quantify the earlier
justification. Our Low and High frequencies are both above average,
however our Middle frequencies are below normal, according to the
average, which we computed.

We determine our average as follows:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(}\FunctionTok{table}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{thin\_youth))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 57
\end{verbatim}

\hypertarget{task-4}{%
\subsubsection{Task 4}\label{task-4}}

\begin{quote}
One would like to know if schooling varies by status. Write a paragraph
explaining whether or not you think this variable varies by status and
detailing how you reached each conclusion.\\
• Include graphs (minimally side by side boxplots) for each group that
support your conclusions.\\
• Include summary statistics (minimally measuring the center and spread)
for each group that support your conclusions.
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{schooling }\SpecialCharTok{\textasciitilde{}}\NormalTok{ lifeexp}\SpecialCharTok{$}\NormalTok{status, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{20}\NormalTok{))}
\FunctionTok{title}\NormalTok{(}\AttributeTok{main =} \StringTok{"schooling and status dependance"}\NormalTok{, )}
\end{Highlighting}
\end{Shaded}

\includegraphics{project-1_files/figure-latex/schooling varies by status-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tapply}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{schooling, lifeexp}\SpecialCharTok{$}\NormalTok{status, summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $Developed
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   13.90   15.30   16.30   16.54   17.70   20.40 
## 
## $Developing
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    5.00   10.70   12.70   12.29   13.97   17.30
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tapply}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{schooling, lifeexp}\SpecialCharTok{$}\NormalTok{status, sd)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Developed Developing 
##   1.647382   2.454269
\end{verbatim}

Notwithstanding the differences in our data and charts, we may conclude
with confidence that educational attainment differs by status.

As compared to the boxplot for poor nations, the schooling years for
rich countries are on the higher end of values with a narrower range.
The range is much wider for emerging nations, with notable outliers at
the lower end and the median (solid) line leaning more toward the upper
end. Not to add that the median in wealthy nations is not comparable to
that in poor nations.Not to add that emerging nations have a wider
dispersion than industrialized nations.

All of this demonstrates that whereas poor nations have a greater
variety and wider distribution of schooling years, with an average of
12.29 years, industrialized countries tend to have more comparable years
of schooling with an average of 16.54 years.

A glance at the average is another option. The average age in wealthy
nations is 16.54 years, compared to 12.29 in developing nations.

\hypertarget{task-5}{%
\subsubsection{Task 5}\label{task-5}}

\begin{quote}
One would like to know if measles varies by continent. Write a paragraph
explaining whether or not you think this variable varies by continent
and detailing how you reached ach conclusion.\\
• Include graphs (minimally side by side boxplots) for each group that
support your conclusions.\\
• Include summary statistics (minimally measuring the center and spread)
for each group that support your conclusions.
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{measles }\SpecialCharTok{\textasciitilde{}}\NormalTok{ lifeexp}\SpecialCharTok{$}\NormalTok{continent, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{2000}\NormalTok{),}
    \AttributeTok{xlab =} \StringTok{"Continent"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Measles Cases Reported by 1000 population"}\NormalTok{,}
    \AttributeTok{main =} \StringTok{"measles and continent dependance"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project-1_files/figure-latex/measles by contient-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tapply}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{measles, lifeexp}\SpecialCharTok{$}\NormalTok{continent, summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $Africa
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0     2.5    60.5  1090.7   222.0 17745.0 
## 
## $Americas
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00    0.00    0.00   13.22    0.00  214.00 
## 
## $Asia
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       0       6      80    4402     615   90387 
## 
## $Europe
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0     1.0     7.5   184.7   107.5  2464.0 
## 
## $Oceania
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0     0.0     0.0    16.1    31.0    74.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tapply}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{measles, lifeexp}\SpecialCharTok{$}\NormalTok{continent, sd)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Africa    Americas        Asia      Europe     Oceania 
##  3293.05568    50.26622 15123.10351   499.49179    25.70970
\end{verbatim}

We may reasonably conclude from our data and charts that the number of
measles cases differs by continent.

The boxplot shows that each continent has a completely unique range,
with multiple outliers (dots) for several continents. This demonstrates
that while measles cases are substantially more dispersed on some
continents, they are not on the Americas and Oceania. They are a lot
smaller.

Our standard deviation, or the ``sd'' in ``tapply,'' determines our
spread. Again, this demonstrates how the distribution of data is
substantially more dispersed for some continents than for others, most
notably the Americas and Oceania. Compared to Africa, Asia, and Europe,
these two continents have spreads that are substantially smaller. The
Americas and Oceania's mean is once again substantially lower than that
for Africa, Asia, and Europe when we look at our mean, which is provided
by the `Mean' function in our'summary' function within `tapply'.

We can observe that the number of measles cases varies greatly by
continent when we combine the spread of data, average of our data, and
plot of our data.

\hypertarget{task-6}{%
\subsubsection{Task 6}\label{task-6}}

\begin{quote}
Two variables that might be studied more in the future are schooling and
measles. It would be helpful to know if these variables are normally
distributed. Write a paragraph for each variable explaining why one
should or should not assume the variable is normally distributed.
Explain in a way that a person with limited statistical knowledge would
understand.\\
• Include all necessary graphs (at least one of a histogram or a Q-Q
Plot with reference line). Explain the implications of the graph(s) in
regards to normality of the variable.\\
• Calculate the skew and kurtosis. Explain the implications of the
values reported in regards to the normality of the variable.\\
• Perform the Shapiro-Wilk Test. State your hypotheses, your decision,
and conclusion. Use a 1\% significance level.
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{schooling, }\AttributeTok{right =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{xlim =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{25}\NormalTok{), }\AttributeTok{main =} \StringTok{"Histogram of Schooling Years"}\NormalTok{,}
    \AttributeTok{xlab =} \StringTok{"Years"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project-1_files/figure-latex/schooling and measles-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{schooling)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  lifeexp$schooling
## W = 0.9957, p-value = 0.9072
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{skewness}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{schooling, }\AttributeTok{type =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.1476361
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kurtosis}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{schooling, }\AttributeTok{type =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.08845119
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{measles)}
\FunctionTok{qqline}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{measles)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project-1_files/figure-latex/schooling and measles-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{measles)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  lifeexp$measles
## W = 0.17902, p-value < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{skewness}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{measles, }\AttributeTok{type =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8.720267
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kurtosis}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{measles, }\AttributeTok{type =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 86.47514
\end{verbatim}

Our schooling data set may appear to be typical for whatever reason. If
you look at the histogram plot up top, you won't see any obvious skews
to the left or right, and there aren't any large tails at the end. The
bell-shaped curve that surrounds all of the data points is centered on
the mean. Also, there are no anomalies. Also, the results of our
Shapiro-Wilk normality test support this likelihood. Only when the
p-value is greater than our significance value is normality taken into
account (in this 0.01). We may think of it as usual because it is. Any
result near to 0 is seen favorably for normalcy when calculating the
skewness, which is a measure of how far to the right or left our data is
pushed.Our skewness, which is -0.1476361, supports normalcy as well.
Last but not least, kurtosis is a tailedness indicator; a value near to
0 indicates symmetry and supports normalcy. Our kurtosis value, which is
-0.08845119, further supports normalcy.

The same cannot be true with our measles data set, though. We utilized a
QQ plot in place of a histogram, which compares actual percentiles to
those predicted by a normal distribution. We can presume normalcy if a
line connects the spots. A big number of points are at stake. The
pronounced tail at the extreme right, however, casts doubt on the
ability to determine normalcy.There must be more testing done. With
regard to our Shapiro-Wilk test, there is sufficient evidence to
conclude that our data are NOT normally distributed because our p-value
is not greater than our significance of 0.01 and is considerably less
than our significance. Last but not least, our values for skewness and
kurtosis are far from zero. They exhibit a skew and a tail that
contradict normalcy.

\hypertarget{task-7}{%
\subsubsection{Task 7}\label{task-7}}

\begin{quote}
Mortality Level.\\
• Create a new ordered factor called mortality\_level that takes on the
value of ``Low'' if the adult.mortality is less than 80, ``Moderate'' if
the adult.mortality is at least 80 and less than 150, and ``High'' if
the adult.mortality is at least 150. Please provide the code in your
project, but you do not need to comment on it.\\
• Write a paragraph explaining whether or not you think mortality\_level
varies by thin\_youth and detail how you reached your conclusion.\\
-- Include graphs (minimally stacked or side-by-side barplots) for each
group that support your conclusions.\\
-- Include summary statistics (such as frequency) by group that support
your conclusions.
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lifeexp}\SpecialCharTok{$}\NormalTok{mortality\_level[lifeexp}\SpecialCharTok{$}\NormalTok{adult.mortality }\SpecialCharTok{\textless{}} \DecValTok{80}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{"Low"}
\NormalTok{lifeexp}\SpecialCharTok{$}\NormalTok{mortality\_level[lifeexp}\SpecialCharTok{$}\NormalTok{adult.mortality }\SpecialCharTok{\textgreater{}=} \DecValTok{80} \SpecialCharTok{\&}\NormalTok{ lifeexp}\SpecialCharTok{$}\NormalTok{adult.mortality }\SpecialCharTok{\textless{}}
    \DecValTok{150}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{"Moderate"}
\NormalTok{lifeexp}\SpecialCharTok{$}\NormalTok{mortality\_level[lifeexp}\SpecialCharTok{$}\NormalTok{adult.mortality }\SpecialCharTok{\textgreater{}=} \DecValTok{150}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{"High"}
\NormalTok{lifeexp}\SpecialCharTok{$}\NormalTok{mortality\_level }\OtherTok{\textless{}{-}} \FunctionTok{ordered}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{mortality\_level, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Low"}\NormalTok{,}
    \StringTok{"Moderate"}\NormalTok{, }\StringTok{"High"}\NormalTok{))}
\FunctionTok{boxplot}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{mortality\_level }\SpecialCharTok{\textasciitilde{}}\NormalTok{ lifeexp}\SpecialCharTok{$}\NormalTok{thin\_youth, }\AttributeTok{ylab =} \StringTok{"Mortality Levels"}\NormalTok{,}
    \AttributeTok{xlab =} \StringTok{"Thin Youth Categories"}\NormalTok{, }\AttributeTok{data =}\NormalTok{ lifeexp}\SpecialCharTok{$}\NormalTok{mortality\_level)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project-1_files/figure-latex/Mortality-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tapply}\NormalTok{(lifeexp}\SpecialCharTok{$}\NormalTok{mortality\_level, lifeexp}\SpecialCharTok{$}\NormalTok{thin\_youth, summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $Low
##      Low Moderate     High 
##       28       17       14 
## 
## $Medium
##      Low Moderate     High 
##        6       19       19 
## 
## $High
##      Low Moderate     High 
##       15       12       41
\end{verbatim}

Certainly, there is sufficient information to demonstrate that the death
rate does differ for the groups of thin kids. The low thin juvenile
groups on the plots frequently have lower death rates. Remember that in
our graphic, 1.0 represents a Low mortality level, 2.0 a Moderate
mortality level, and 3.0 a High mortality level. When greater death
rates are associated with higher categories of thinness, everything is
mirrored on the other side.

We have a clearer perspective after looking at our summary. Lower levels
of thinness were correlated with lower rates/counts of low mortality.
When we move up the thinness scale, mortality tends to increase.As we
reach a medium level of thinness, moderate and high death rates
outnumber low mortality rates. In contrast, consider great thinness.
While the thinness group was categorized as having a high death rate,
there were more than 40 incidents documented.

\end{document}
